### ISSUE TITLE
Tokenizer does not recognize multi-character identifiers after keyword

### ISSUE THREAD

**Issue by UltrioG** [UltrioG/Ultrio-Testlang#9]
Exactly as the title says, the tokenizer does not tokenize any multi-character identifiers after a keyword.
e.g.
```
var at
```
yields only "var" in the tokens.

**Comment by UltrioG** [comment]
Update: this issue applies to anything that uses literal matching, not just keywords. Doesn't seem to affect separators for some reason though.

**Comment by J-W-CDSJ6** [comment]
So that means it's something about the matching.

**Comment by J-W-CDSJ6** [comment]
Issue closed. Mistake was at line 127 of the tokenizer, where a break was used instead of a continue equivalent.

**Comment by J-W-CDSJ6** [comment]
Woo hoo
